version: '3.8'
services:
  client:
    stdin_open: true
    build: client/
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
       -  "/app/node_modules"
       -  "./:/app"
  server:
    build: server/
    volumes:
      - "./:/server"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on: 
      - db
  db:
    image: amazon/dynamodb-local
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile
    ports:
    - ${DB_ADM_PORT}:${DB_ADM_PORT}
    environment:
      - DYNAMO_ENDPOINT=${DB_ENDPOINT}
      - AWS_REGION=${DB_REGION_NAME}
      - AWS_ACCESS_KEY_ID=${DB_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${DB_SECRET_ACCESS_KEY}
    depends_on:
      - db